Repository JuanGidoni/mobiliarium, pull requests merged in 2025-04, with the labels that each got.

#18 feature/3_header_implementation
  package-lock.json
  package.json
  src/App.jsx
  src/components/Header.jsx
  src/components/README.md
  src/index.css
  src/main.jsx
Labels: component

#20 feature/19_create_verify_mr_base
  .github/CODEOWNERS
  .github/checkMR.yml
  .github/syncDevelop.yml
Labels: architecture

#21 feature/4_footer_implementation
  src/App.jsx
  src/components/Footer.jsx
  src/index.css
Labels: component

#28 Develop into main #1
  .github/CODEOWNERS
  .github/workflows/check-base-branch.yml
  .github/workflows/deployment.yml
  .github/workflows/sync-develop.yml
  .github/workflows/sync-main.yml
  .github/workflows/validations.yml
  babel.config.cjs
  eslint.config.js
  index.html
  jest.config.cjs
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/App.test.js
  src/assets/README.md
  src/assets/react.svg
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/Navigation.jsx
  src/components/README.md
  src/index.css
  src/main.jsx
  src/pages/README.md
  src/routes/README.md
  src/services/README.md
Labels: architecture, deploy

#31 fix/29_deploy_and_sync
  .github/workflows/deployment.yml
  .github/workflows/sync-develop.yml
Labels: architecture

#55 develop into main #9 (fix)
  .github/workflows/deployment.yml
  babel.config.cjs
  babel.config.json
  eslint.config.js
  index.html
  jest.config.cjs
  jsconfig.json
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/assets/Logo.png
  src/components/Header.jsx
  src/components/button/Button.css
  src/components/button/Button.jsx
  src/components/error/ErrorPage.css
  src/components/error/ErrorPage.jsx
  src/components/footer/Footer.jsx
  src/components/header/Header.css
  src/components/header/Header.jsx
  src/components/header/Header.test.jsx
  src/components/navigation/Navigation.css
  src/components/navigation/Navigation.jsx
  src/index.css
  src/layouts/Layout.jsx
  src/main.jsx
  src/pages/home/HomePage.css
  src/pages/home/HomePage.jsx
  src/routes/AppRoutes.jsx
  src/routes/routes.jsx
  src/styles/index.css
  vite.config.js
  vitest.setup.js
Labels: deploy

#70 develop into main (0.1.0)
  .env
  .github/workflows/deployment.yml
  git-cliff.toml
  package-lock.json
  package.json
  src/App.jsx
  src/components/filter/Filter.css
  src/components/filter/Filter.jsx
  src/components/footer/Footer.css
  src/components/footer/Footer.jsx
  src/components/image/Image.jsx
  src/components/navigation/Navigation.css
  src/components/navigation/Navigation.jsx
  src/components/productCard/ProductCard.css
  src/components/productCard/ProductCard.jsx
  src/components/search/Search.css
  src/components/search/Search.jsx
  src/pages/home/HomePage.css
  src/pages/home/HomePage.jsx
  src/pages/home/useHomePageLogic.jsx
  src/services/api.js
  src/store/items/itemsSlice.js
  src/store/store.js
Labels: deploy
